### ISSUE TITLE
Possible directory / path traversal

### ISSUE THREAD

**Issue by kdslkdsaldsal** [oxpus/Basic-Statistics#10]
Hi,

running phpBB 3.2.1 with the current master of Basic-Statistics. Based on https://github.com/oxpus/Basic-Statistics/issues/9 i've tried to do some short manipulations like:

1. Created /tmp/test_view.html
2. Opened https://www.example.com/forum/basicstats/?mode=../../../../../../../tmp/test

It seems some built in mechanisms of phpBB is kicking in:

```
Looks like you try to load a template outside configured directories (../../../../../../../tmp/test_view.html).
```

but still it might worth to sanitize any input where users are able to put in malicious / arbitrary files and patterns.

**Comment by oxpus** [comment]
Package updated.
Missing mode or using wrong mode value will now open default month view.

**Comment by kdslkdsaldsal** [comment]
Nice, thanks. Whitelisting of the allowed modes is even better 👍
