### ISSUE TITLE
Prosilver: Move URL of statistics to Quick links

### ISSUE THREAD

**Issue by RealRancor** [oxpus/Basic-Statistics#2]
Hi,

the mod is currently adding the link to app.php/basicstats/ next to the "Delete all board cookies" link at the footer of Prosilver based themes.

On such themes the location could be placed within the "Quick links".

**Comment by oxpus** [comment]
The Extension was build just for founders so the link takes place to a not prominent location into the footer. 
But fiel free to rearrange the link to the stats into the Quick links

**Comment by RealRancor** [comment]
Hi,

thats fine with me. I just have renamed https://github.com/oxpus/Basic-Statistics/blob/master/oxpus/basicstats/styles/prosilver/template/event/overall_footer_timezone_after.html to navbar_header_quick_links_after.html which works fine for me.
