### ISSUE TITLE
Support "URL rewrite" option of phpBB

### ISSUE THREAD

**Issue by RealRancor** [oxpus/Basic-Statistics#3]
Hi,

within the ACP there is a setting for "Enable URL Rewriting" (See: https://www.phpbb.com/support/docs/en/3.1/ug/adminguide/general_server/) which is rewriting an extension URL within phpBB from e.g. https://example.com/apps.php/extensionname to https://example.com/extensionname

The currently generated URL of the extension within the footer doesn't respect this setting.

**Comment by RealRancor** [comment]
@oxpus It would be great if issues are not closed without any comments / hints why it was closed.

If this won't be implemented or the issue tracker here is the wrong place i'm fine. But at least a short notice would be really helpful.

**Comment by oxpus** [comment]
Sorry, my mistake. I've used a malfunction client. The topics should not be closed by me :-(

**Comment by oxpus** [comment]
For URL rewriting: I've still not testen

**Comment by RealRancor** [comment]
Hi,

no worries. I just thought it was closed on purpose.

I've just tested https://github.com/oxpus/Basic-Statistics/commit/d48c740bffe86d2c92d098b2d77c1111bc427e5a and works so i'm closing this one. Thanks!
