### ISSUE TITLE
Provide permissions for stats access

### ISSUE THREAD

**Issue by RealRancor** [oxpus/Basic-Statistics#4]
Hi,

currently only owners are allowed to access the statistics:

https://github.com/oxpus/Basic-Statistics/blob/5d5a29747d5f60a342ce1348fcda4692a2e6b8ba/oxpus/basicstats/controller/main.php#L55-L58

It would be great if the extension introduce a own permission for the app.

**Comment by oxpus** [comment]
No, this is fixed in the extension. The load will be to high even all users can view the stats pages.

**Comment by RealRancor** [comment]
Sure, thats fine for me. Quick'n'dirty hack for this. Replace:

https://github.com/oxpus/Basic-Statistics/blob/5d5a29747d5f60a342ce1348fcda4692a2e6b8ba/oxpus/basicstats/controller/main.php#L55

with ``if ($this->user->data['user_type'] == USER_BOT || $this->user->data['user_id'] == ANONYMOUS)``
