### ISSUE TITLE
Dates are displayed in ENGLISH

### ISSUE THREAD

**Issue by Galixte** [oxpus/Basic-Statistics#6]
Hi @oxpus,

in FRENCH i have a problem with dates like ```june 2017``` which are displayed in english.

Could you make in sort to change the PHP code to display the dates in the language used on the board, please ?

I know it’s in ```main.php``` file but i didn’t find which part of code has to be fixed.

**Comment by oxpus** [comment]
The feed will read the post from the source and does not reformat it.
There's no function to format any date.
Can you please give an example?

**Comment by Galixte** [comment]
Hi @oxpus,

not the format the text for the dates is displayed in english while my board language is FRENCH, example : 
![inked2017-06-20 05_05_01-forum de test - statistiques statistiques mensuelles - opera_li](https://user-images.githubusercontent.com/7478287/27314879-b068f406-5576-11e7-8a42-a32d9587fb8f.jpg)
![inked2017-06-20 05_06_31-_li](https://user-images.githubusercontent.com/7478287/27314880-b084cd3e-5576-11e7-90e0-72fb4862cb14.jpg)

**Comment by oxpus** [comment]
Package fixed.
The month names shall now be formated within the user language.

**Comment by Galixte** [comment]
Thanks chief 👍
