### ISSUE TITLE
Information disclusore of file system path

### ISSUE THREAD

**Issue by kdslkdsaldsal** [oxpus/Basic-Statistics#9]
Hi,

running phpBB 3.2.1 with the current master of Basic-Statistics. When opening an URL like:

https://www.example.com/forum/basicstats/?mode= (without a mode)

the following error is shown exposing the full path on the current filesystem:

```
Unable to find template "_view.html" (looked into: /var/www/forum/ext/oxpus/basicstats/styles/prosilver/template, /var/www/forum/styles/prosilver/template, /var/www/forum/styles/prosilver/theme, /var/www/forum/styles/all/template).
```

**Comment by oxpus** [comment]
Package updated.
Missing mode or using wrong mode value will now open default month view.

**Comment by kdslkdsaldsal** [comment]
Nice, thanks. Whitelisting of the allowed modes is even better 👍
